# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wick < Formula
  desc ""
  homepage "https://github.com/s-things/wick"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/s-things/wick/releases/download/v0.5.0/wick_0.5.0_macOS_arm64.tar.gz"
      sha256 "7d31315be1bf534a30491671cc503eb8793d78eb277baf6e63a8011f9eafcf53"

      def install
        bin.install "wick"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/s-things/wick/releases/download/v0.5.0/wick_0.5.0_macOS_x86_64.tar.gz"
      sha256 "03a9df668c5fa83256d536caae38590fed2cbc802e09af37664627b0d5e2959f"

      def install
        bin.install "wick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/s-things/wick/releases/download/v0.5.0/wick_0.5.0_Linux_x86_64.tar.gz"
      sha256 "cbadf956b7e62078005d2f6b366d6a0d8ee8fc5071dd51493a38ad8130254ad6"

      def install
        bin.install "wick"
      end
    end
  end

  depends_on "git"
  depends_on "go"
end
