# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wick < Formula
  desc ""
  homepage "https://github.com/codebasepk/wick"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codebasepk/wick/releases/download/v0.1.1/wick_0.1.1_macOS_arm64.tar.gz"
      sha256 "1b5d85254aaf41e4ff6a7dd9bffde3b6412c951d10c0b82b61d5741848af3aca"

      def install
        bin.install "wick"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/codebasepk/wick/releases/download/v0.1.1/wick_0.1.1_macOS_x86_64.tar.gz"
      sha256 "d36c33062a79b59bdf749a0259331802a4bfd58cdeef1c9eac546ffe1d50297b"

      def install
        bin.install "wick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/codebasepk/wick/releases/download/v0.1.1/wick_0.1.1_Linux_x86_64.tar.gz"
      sha256 "575ed3a4c96701d6ccffbce6e7c0cc9de0014d0a65d116fed8a00c2dcc074606"

      def install
        bin.install "wick"
      end
    end
  end

  depends_on "git"
  depends_on "go"
end
